# Generated by Django 5.2 on 2025-05-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En_attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En_attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
