# Generated by Django 5.2 on 2025-05-07 06:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_statut_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilitemedecin',
            name='jour',
            field=models.DateField(),
        ),
    ]
